'use strict';

const GROUND_WIDTH = 480;
const GROUND_HEIGHT = 80;

const GAME_STATES = {
  START_SCREEN: 0,
  GAME_SCREEN: 1,
  END_SCREEN: 2,
}

const PIPE_WIDTH = 82;
const PIPE_HEIGHT = 475;
const PIPE_DIFFERENCE = 120;
const PIPE_DISTANCE = 100;
const MINIMUM_POSITION_OFFSET = 50;
const PIPE_INTERVAL = 1000;

const BIRD_WIDTH = 45;
const BIRD_HEIGHT = 32;

const BACKGROUND_SCROLL_OFFSET = 80;
